# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Fire Ready Aim
email: marc.wright@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Ramblings on music and code
baseurl: "/firereadyaim" # the subpath of your site, e.g. /blog
url: "http://marcwright.github.io/firereadyaim/" # the base hostname & protocol for your site
twitter_username: m4rc
github_username:  marcwright

# Build settings
markdown: kramdown
